repos:
  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort

  - repo: https://github.com/pycqa/flake8
    rev: 7.2.0
    hooks:
      - id: flake8

  - repo: local
    hooks:
      - id: flake8-html
        name: flake8 with HTML report
        entry: bash -c 'flake8 --format=html --htmldir=flake8-report'
        language: system
